server:
  port: 8080

spring:
  application:
    name: fitmate

  datasource:
    url: jdbc:mysql://localhost:3306/fitmate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method