package com.fitmate.backend.member.domain;

public enum GoalStrategy {

    // 체지방 감량
    FAT_LOSS_STRENGTH_FOCUS,
    FAT_LOSS_CARDIO_FOCUS,
    FAT_LOSS_BALANCED,

    // 근육 성장
    MUSCLE_GAIN_HYPERTROPHY_FOCUS,
    MUSCLE_GAIN_BODY_PART_FOCUS,
    MUSCLE_GAIN_FULL_BODY_BALANCED,

    // 근력 향상
    STRENGTH_BIG_THREE_FOCUS,
    STRENGTH_UPPER_BODY_FOCUS,
    STRENGTH_LOWER_BODY_FOCUS,
    STRENGTH_OVERALL,

    // 신체 재구성
    RECOMPOSITION_FAT_LOSS_PRIORITY,
    RECOMPOSITION_MUSCLE_GAIN_PRIORITY,
    RECOMPOSITION_BALANCED,

    // 체력 향상
    FITNESS_CARDIORESPIRATORY_FOCUS,
    FITNESS_MUSCULAR_ENDURANCE_FOCUS,
    FITNESS_OVERALL,

    // 운동 습관 형성
    HABIT_SHORT_AND_FREQUENT,
    HABIT_THREE_TIMES_A_WEEK,
    HABIT_GRADUAL_INTENSITY
}